---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  # This is necessary to ensure the _first_ node is indeed master
  order: sorted
  gather_facts: yes
  tasks:
    - name: Define vrrp nic
      set_fact:
        vrrp_nic: "{{ ((facts['interfaces'] | reject('equalto','lo')) | difference([ansible_facts['default_ipv4'].interface]))[0] | string }}"

    - name: Show ansible facts
      debug:
        var: ansible_facts
        verbosity: 3

    - name: Ensure the first node is master
      assert:
        that:
          - "'ipv4_secondaries' in ansible_facts[vrrp_nic]
          - "ansible_facts[vrrp_nic].['ipv4_secondaries'][0]['address'] == '192.168.33.2'"
      when: inventory_hostname == ansible_play_hosts[0]
